spring:
  application:
    name: WellCare
  datasource:
    url: jdbc:mysql://localhost:3306/dev_wellcare?useSSL=false&serverTimezone=UTC
    username: root
    password: ProBen@1309%
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: U2VjdXJlS2V5X0Zvcl93ZWxsY2FyZV9KV1RfQXV0aF9UaGlzSXMxMjM0NQ==
  expiration: 3600000

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
